remote_theme: pages-themes/slate@v0.2.0
description: Materiały pomocnicze do nauki hebrajskiego
author: Maciek Świszczowski
include:
  - assets/css/styles.css
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default